name: 'CI/CD'

on:
  push:
    branches: [main, release]
  pull_request:
    branches: [main, release]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dependencies:
    name: Preflight
    uses: ./.github/workflows/dependencies.yaml

  lint-check:
    name: Lint check
    runs-on: ubuntu-latest
    needs: [dependencies]

    steps:
      - uses: actions/checkout@v3

      - name: Load cached node_modules
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: '**/node_modules'
          key: ${{ needs.dependencies.outputs.node-version }}_${{ runner.os }}_modules_${{ hashFiles('**/yarn.lock') }}

      - name: Lint
        run: npm run lint:ci
      - uses: actions/upload-artifact@v3
        with:
          name: eslint-report
          path: eslint-report.json

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v3

      - name: Load cached node_modules
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: '**/node_modules'
          key: ${{ needs.dependencies.outputs.node-version }}_${{ runner.os }}_modules_${{ hashFiles('**/yarn.lock') }}

      - name: Test
        run: npm run test:ci

      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage